### ISSUE TITLE
combustible,noncombustible

### ISSUE THREAD

**Issue by pnrobinson** [drseb/phenopposites#5]
There are lots of antonyms that do not seem to apply to human phenotypes. 
I would suggest removing the following unless they exist somewhere in the HPO definitions.

asynchronous,synchronous
active,inactive
difficult,easy
quick,slow
huge,tiny
more,less
never,always
old,young
down,up
coiled,uncoiled
auxotrophic,prototrophic
invariant,variant
conspicuous,inconspicuous
good,bad
insensitive,sensitive
oriented,disoriented
crowded,uncrowded
continuous,discontinuous
lethal,viable
balanced,unbalanced
coordinated,uncoordinated
permeable,impermeable
porous,non-porous
consistent,inconsistent
susceptibility,resistance
susceptible,insusceptible
concentrated,unconcentrated
damaged,undamaged
elastic,inelastic
structured,unstructured
aerobic,anaerobic
magnetic,non-magnetic
hydrophobic,hydrophilic
front,back
differentiated,undifferentiated
active,inactive
minimal,maximal
minimally,maximally
distributed,undistributed
serrated,unserrated
adequate,inadequate
responsive,unresponsive
soluble,insoluble
inflated,uninflated
interrupted,uninterrupted
complete,incomplete
sufficient,insufficient
drinkable,undrinkable
stratified,unstratified
discriminate,indiscriminate
contiguous,discontiguous
ornamented,unornamented
polar,nonpolar
efficient,inefficient
organized,disorganized
potable,non-potable
modified,unmodified
fragile,non-fragile
discriminate,indiscriminate
functional,non-functional
adhesive,non-adhesive
phosphorylated,dephosphorylated
compatible,incompatible
flexible,inflexible
resinous,non-resinous
contractile,non-contractile
condensed,decondensed
necessary,unnecessary
branched,unbranched
divided,undivided
edible,inedible
lumenized,unlumenized
aromatic,non-aromatic
transparent,non-transparent
micro,macro

**Comment by iamkoehler** [comment]
This is not an HPO-specific project. These lists may be used for a lot of other phenotype and gene function ontologies ontology.
